kind: pipeline
type: ssh
name: deploy

server:
  host:
    from_secret: host
  user:
    from_secret: user
  ssh_key:
    from_secret: ssh_key

platform:
  os: freebsd
  arch: amd64

steps:
- name: deploy to develop
  commands:
  - "cd /data/websites/danschmid-develop"
  - git pull
  - composer install
  - yarn
  - yarn dev
  - service nginx restart
  - service php-fpm restart
  when:
    branch:
    - develop

- name: deploy to master
  commands:
  - "cd /data/websites/danschmid"
  - git pull
  - composer install
  - yarn
  - yarn prod
  - service nginx restart
  - service php-fpm restart
  when:
    branch:
    - master

---
kind: pipeline
type: docker
name: ci/release
steps:
- name: auto-release
  image: xena/gitea-release
  settings:
    auth_username: daniel
    changelog_path: ./CHANGELOG.md
    gitea_server: https://git.danschmid.de
    gitea_token:
      from_secret: GITEA_TOKEN
  when:
    event:
      - push
    branch:
      - master

---
kind: pipeline
type: docker
name: telegram

steps:
- name: telegram notify
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: telegram_token
    to:
      from_secret: telegram_to
      when:
    status: [ success, failure ]
  format: markdown
  message: >
    {{#success build.status}}
    ✅ Build #{{build.number}} of `{{repo.name}}` succeeded.

    📝 Commit by {{commit.author}} on `{{commit.branch}}`:

    ```
    {{commit.message}}
    ```

    🌐 {{ build.link }}
    {{else}}
    ❌ Build #{{build.number}} of `{{repo.name}}` failed.

    📝 Commit by {{commit.author}} on `{{commit.branch}}`:

    ```
    {{commit.message}}
    ```

    🌐 {{ build.link }}
    {{/success}}
depends_on:
- deploy
